from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health_view),
    path("api/health/", views.health_view),
    path("auth/login/", views.login_view),
    path("api/auth/login/", views.login_view),
    path("auth/register/", views.register_view),
    path("api/auth/register/", views.register_view),
    path("auth/me/", views.auth_me_view),
    path("api/auth/me/", views.auth_me_view),
    path("users/", views.users_view),
    path("animals/", views.animals_view),
    path("api/animals/", views.animals_view),
    path("animals/<str:animal_id>/", views.animal_detail_view),
    path("api/animals/<str:animal_id>/", views.animal_detail_view),
    path("detections/", views.detections_view),
    path("api/detections/", views.detections_view),
    path("alerts/", views.alerts_view),
    path("history/", views.history_view),
    path("api/history/", views.history_view),
    path("analytics/summary/", views.analytics_summary_view),
    path("api/analytics/", views.analytics_summary_view),
    path("api/analytics/summary/", views.analytics_summary_view),
    path("detect/image/", views.detect_image_view),
    path("api/identify/", views.detect_image_view),
    path("api/detect/image/", views.detect_image_view),
    path("upload/video/", views.upload_video_view),
    path("api/upload/video/", views.upload_video_view),
    path("start-detection/", views.start_detection_view),
    path("stop-detection/", views.stop_detection_view),
    path("stats/", views.stats_view),
    path("cameras/", views.cameras_view),
    path("settings/", views.update_settings_view),
    path("reports/detections.csv", views.report_detections_csv_view),
    path("api/reports/detections.csv", views.report_detections_csv_view),
    path("reports/detections.pdf", views.report_detections_pdf_view),
    path("api/reports/detections.pdf", views.report_detections_pdf_view),
    path("video-feed/", views.video_feed_view),
    path("latest-detection-image/", views.latest_detection_image_view),
]
