# Generated by Django 5.2.15 on 2026-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_registered_animals', models.PositiveIntegerField(default=0)),
                ('total_identifications', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('species_distribution', models.JSONField(blank=True, default=dict)),
                ('daily_detections', models.JSONField(blank=True, default=dict)),
                ('monthly_detections', models.JSONField(blank=True, default=dict)),
                ('top_animals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_a_snapsho_8bc780_idx')],
            },
        ),
    ]
