# Generated by Django 5.2.15 on 2026-06-06 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='identification/uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])])),
                ('uploaded_video', models.FileField(blank=True, upload_to='identification/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv', 'webm'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_species', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('match_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('similarity_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('top_k_matches', models.JSONField(blank=True, default=list)),
                ('feature_scores', models.JSONField(blank=True, default=dict)),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identified_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identification_results', to='animals.animal')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='identification.identificationjob')),
            ],
            options={
                'ordering': ['-detection_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='identificationjob',
            index=models.Index(fields=['requested_by', 'created_at'], name='identificat_request_73e208_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationjob',
            index=models.Index(fields=['status', 'created_at'], name='identificat_status_fa6c22_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationresult',
            index=models.Index(fields=['identified_animal', 'detection_timestamp'], name='identificat_identif_1c9053_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationresult',
            index=models.Index(fields=['detected_species', 'detection_timestamp'], name='identificat_detecte_906256_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationresult',
            index=models.Index(fields=['confidence_score'], name='identificat_confide_9ae758_idx'),
        ),
    ]
