# Generated by Django 5.2.15 on 2026-06-06 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_animal_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('species', models.CharField(db_index=True, max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_type', models.CharField(choices=[('full', 'Full Body'), ('face', 'Face'), ('nose', 'Nose'), ('ears', 'Ears'), ('pattern', 'Pattern'), ('other', 'Other')], default='full', max_length=32)),
                ('is_reference', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('full', 'Full'), ('forehead', 'Forehead'), ('eyes', 'Eyes'), ('nose', 'Nose'), ('ears', 'Ears'), ('pattern', 'Pattern')], default='full', max_length=32)),
                ('embedding_vector', models.JSONField()),
                ('model_name', models.CharField(default='resnet50', max_length=128)),
                ('vector_dimension', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='animals.animal')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings', to='animals.animalimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'breed'], name='animals_ani_species_60bf00_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['created_by', 'registration_date'], name='animals_ani_created_7691c6_idx'),
        ),
        migrations.AddIndex(
            model_name='animalimage',
            index=models.Index(fields=['animal', 'image_type'], name='animals_ani_animal__99cd68_idx'),
        ),
        migrations.AddIndex(
            model_name='animalimage',
            index=models.Index(fields=['upload_date'], name='animals_ani_upload__3f70be_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricembedding',
            index=models.Index(fields=['animal', 'region'], name='animals_bio_animal__d8ae3c_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricembedding',
            index=models.Index(fields=['model_name', 'created_at'], name='animals_bio_model_n_f287c6_idx'),
        ),
    ]
