const state = { user: null, page: "Dashboard", stats: {}, analytics: {}, animals: [], detections: [], alerts: [], cameras: [], online: false };
let typeChart = null;
let trendChart = null;

const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const pct = (v) => `${Math.round((Number(v) || 0) * 100)}%`;
const fmt = (v) => new Intl.NumberFormat().format(Number(v) || 0);

function toast(message, error = false) {
  const root = $("toast-root"); if (!root) return;
  const el = document.createElement("div"); el.className = `toast-card ${error ? "error" : ""}`; el.textContent = message;
  root.appendChild(el); setTimeout(() => el.remove(), 3000);
}
function loginView() {
  return `<div class="login"><div class="panel login-card"><div class="brand"><div class="brand-mark">A</div><div><h2>Animal Detection</h2><small>Detection & re-identification dashboard</small></div></div><label class="form-label">Email</label><input id="email" class="form-control mb-3" type="email" placeholder="admin@demo.com"><label class="form-label">Password</label><input id="password" class="form-control mb-4" type="password" placeholder="Password"><button id="login" class="btn btn-brand w-100">Sign in</button><p class="muted small mt-3 mb-0">Use the credentials configured on your local backend.</p></div></div>`;
}
function nav() {
  return `<aside class="sidebar"><div class="brand"><div class="brand-mark">A</div><div><h2>Animal Detection</h2><small>${esc(state.user?.full_name || "User")}</small></div></div><div class="nav-list">${PAGES.map(p => `<button class="nav-btn ${state.page === p ? "active" : ""}" data-page="${p}">${p}</button>`).join("")}</div><button id="logout" class="btn btn-outline-light mt-auto">Logout</button></aside>`;
}
function dashboard() {
  const a = state.analytics || {};
  return `<div class="stats"><div class="stat"><h3>Animals</h3><strong>${fmt(state.stats.total_animals)}</strong></div><div class="stat"><h3>Detections</h3><strong>${fmt(state.stats.total_detections)}</strong></div><div class="stat"><h3>Cameras</h3><strong>${fmt(state.cameras.length)}</strong></div><div class="stat"><h3>Alerts</h3><strong>${fmt(state.stats.total_alerts)}</strong></div></div><div class="grid"><div class="panel"><h5>Animal distribution</h5><canvas id="typeChart" height="220"></canvas></div><div class="panel"><h5>Daily detections</h5><canvas id="trendChart" height="220"></canvas></div></div><div class="panel mt-3"><h5>Top detected animals</h5><div class="table-wrap"><table class="table-custom"><thead><tr><th>Animal ID</th><th>Detections</th></tr></thead><tbody>${(a.top_animals || []).map(x => `<tr><td>${esc(x.animal_id)}</td><td>${fmt(x.count)}</td></tr>`).join("") || `<tr><td colspan="2" class="empty">No detection data yet.</td></tr>`}</tbody></table></div></div>`;
}
function live() { const running = Boolean(state.stats.detection?.running); return `<div class="grid"><div class="panel"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Live camera</h5><span class="badge-soft">${running ? "Running" : "Stopped"}</span></div><img class="feed" src="${API_BASE_URL}/video-feed" alt="Live camera feed"><div class="d-flex gap-2 mt-3"><button id="start" class="btn btn-brand">Start detection</button><button id="stop" class="btn btn-outline-light">Stop</button></div></div><div class="panel"><h5>Runtime</h5><p class="muted">Source: ${esc(state.stats.detection?.source ?? state.cameras.default_source ?? "—")}</p><p>FPS: <strong>${Number(state.stats.detection?.last_fps || 0).toFixed(1)}</strong></p><p>Processed frames: <strong>${fmt(state.stats.detection?.processed_frames)}</strong></p></div></div>`; }
function animals() { return `<div class="grid">${state.animals.map(a => `<div class="panel"><div class="d-flex justify-content-between"><div><h5>${esc(a.animal_id || a.id || "Unknown")}</h5><div class="muted">${esc(a.animal_type || a.species || "Unknown")}</div></div><span class="badge-soft">${esc(a.status || "Active")}</span></div><hr><p>Health score: <strong>${fmt(a.health_score ?? a.overall_health_score)}%</strong></p><p class="muted mb-0">Average similarity: ${pct(a.average_similarity_score ?? a.average_similarity)}</p></div>`).join("") || `<div class="panel empty">No animal profiles available yet.</div>`}</div>`; }
function history() { return `<div class="panel"><div class="row g-2 mb-3"><div class="col-md-4"><input id="filterType" class="form-control" placeholder="Species/type"></div><div class="col-md-4"><input id="filterAnimal" class="form-control" placeholder="Animal ID"></div><div class="col-md-4"><input id="filterConfidence" class="form-control" type="number" min="0" max="1" step=".01" value="0" placeholder="Min confidence"></div></div><button id="filter" class="btn btn-brand mb-3">Apply filters</button><div class="table-wrap"><table class="table-custom"><thead><tr><th>Time</th><th>Animal</th><th>Type</th><th>Confidence</th><th>Similarity</th><th>Camera</th></tr></thead><tbody>${state.detections.map(d => `<tr><td>${esc(d.timestamp)}</td><td>${esc(d.animal_id)}</td><td>${esc(d.animal_type)}</td><td>${pct(d.confidence)}</td><td>${pct(d.similarity_score ?? d.similarity)}</td><td>${esc(d.camera_id || "—")}</td></tr>`).join("") || `<tr><td colspan="6" class="empty">No detections found.</td></tr>`}</tbody></table></div></div>`; }
function reports() { return `<div class="grid"><div class="panel"><h5>Reports</h5><div class="d-grid gap-2"><a class="btn btn-brand" href="${API_BASE_URL}/api/reports/detections.csv" target="_blank">Download CSV</a><a class="btn btn-outline-light" href="${API_BASE_URL}/api/reports/detections.pdf" target="_blank">Download PDF</a></div></div><div class="panel"><h5>Image analysis</h5><input id="image" class="form-control mb-3" type="file" accept="image/*"><button id="analyze" class="btn btn-brand">Analyze image</button><div id="preview" class="mt-3"></div></div></div>`; }
function profile() { return `<div class="panel"><h5>Profile</h5><p><b>Name:</b> ${esc(state.user?.full_name)}</p><p><b>Email:</b> ${esc(state.user?.email)}</p><p><b>Role:</b> ${state.user?.is_admin ? "Administrator" : "User"}</p></div>`; }
function settings() { const value = Number(state.stats.confidence_threshold ?? .35); return `<div class="panel"><h5>Detection settings</h5><label class="form-label">Confidence threshold</label><input id="threshold" class="form-range" type="range" min="0" max="1" step=".01" value="${value}"><p class="muted">Current: <span id="thresholdValue">${pct(value)}</span></p><button id="saveSettings" class="btn btn-brand">Save</button></div>`; }
function pageView() { return ({Dashboard:dashboard,Live:live,Animals:animals,History:history,Reports:reports,Profile:profile,Settings:settings}[state.page] || dashboard)(); }
async function loadData() { try { const [stats, animalsRes, alerts, detections, analytics, cameras] = await Promise.all([apiGet("/stats"), apiGet("/api/animals/"), apiGet("/alerts"), apiGet("/api/detections/?limit=200"), apiGet("/api/analytics/"), apiGet("/cameras")]); state.online = true; state.stats = stats || {}; state.animals = animalsRes?.items || []; state.alerts = alerts?.items || []; state.detections = detections?.items || []; state.analytics = analytics || {}; state.cameras = cameras || {}; } catch (e) { state.online = false; toast("Backend is unavailable. Start FastAPI and refresh.", true); } }
function charts() { if (typeof Chart === "undefined") return; if (typeChart) typeChart.destroy(); if (trendChart) trendChart.destroy(); const c1=$("typeChart"), c2=$("trendChart"); if(c1){ const a=state.analytics.by_type||{}; typeChart=new Chart(c1,{type:"doughnut",data:{labels:Object.keys(a),datasets:[{data:Object.values(a)}]},options:{plugins:{legend:{labels:{color:"#edf6ff"}}}}}); } if(c2){ const a=state.analytics.daily_counts||{}; const keys=Object.keys(a).sort(); trendChart=new Chart(c2,{type:"line",data:{labels:keys,datasets:[{data:keys.map(k=>a[k]),tension:.3}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:"#9fb3c8"}},y:{ticks:{color:"#9fb3c8"}}}}}); } }
function render() { const root=$("app"); if(!state.user){root.innerHTML=loginView(); bind(); return;} root.innerHTML=`<div class="app-shell">${nav()}<main class="main"><div class="header"><div><h1>${state.page}</h1><div class="muted">${state.online ? "Backend connected" : "Backend unavailable"}</div></div><button id="refresh" class="btn btn-outline-light">Refresh</button></div>${pageView()}</main></div>`; bind(); charts(); }
function bind() { document.querySelectorAll("[data-page]").forEach(b=>b.onclick=async()=>{state.page=b.dataset.page;render();}); const login=$("login"); if(login) login.onclick=async()=>{try{const r=await apiPost("/api/auth/login/",{email:$("email").value,password:$("password").value});localStorage.setItem(STORAGE_KEY,r.access_token);await session();}catch(e){toast("Sign in failed.",true);}}; const logout=$("logout");if(logout)logout.onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.user=null;render();}; const refresh=$("refresh");if(refresh)refresh.onclick=async()=>{await loadData();render();}; const start=$("start");if(start)start.onclick=async()=>{try{const r=await apiPost("/start-detection",{source:0,show_window:false});toast(r?.started?"Detection started":"Detection did not start",!r?.started);await loadData();render();}catch(e){toast("Unable to start detection.",true);}}; const stop=$("stop");if(stop)stop.onclick=async()=>{try{await apiPost("/stop-detection",{});toast("Detection stopped");await loadData();render();}catch(e){toast("Unable to stop detection.",true);}}; const filter=$("filter");if(filter)filter.onclick=async()=>{const q=new URLSearchParams({limit:200,min_confidence:Number($("filterConfidence").value)||0});if($("filterType").value)q.set("animal_type",$("filterType").value);if($("filterAnimal").value)q.set("animal_id",$("filterAnimal").value);try{const r=await apiGet(`/api/history/?${q}`);state.detections=r?.items||[];render();}catch(e){toast("Could not load history.",true);}}; const analyze=$("analyze");if(analyze)analyze.onclick=async()=>{const f=$("image").files[0];if(!f)return toast("Select an image first.",true);try{const r=await apiUpload("/api/identify/",f);$("preview").innerHTML=r?.annotated_image?`<img src="${r.annotated_image}" class="img-fluid rounded-4" alt="Detection result">`:"No annotated image returned.";toast("Image analyzed");}catch(e){toast("Image analysis failed.",true);}}; const range=$("threshold");if(range)range.oninput=()=>$("thresholdValue").textContent=pct(range.value); const save=$("saveSettings");if(save)save.onclick=async()=>{try{await apiPost("/settings",{confidence_threshold:Number($("threshold").value)});toast("Settings saved");await loadData();render();}catch(e){toast("Could not save settings.",true);}}; }
async function session(){try{state.user=await apiGet("/api/auth/me/");await loadData();render();}catch(e){localStorage.removeItem(STORAGE_KEY);state.user=null;render();}}
(async()=>{if(localStorage.getItem(STORAGE_KEY))await session();else render();})();
